### ISSUE TITLE
Openening a locale in internet explorer 11 causes a JS error

### ISSUE THREAD

**Issue by Nick-Triller** [anthonynsimon/parrot#37]
Tested in IE 11.0.9600.18449, update version 11.0.35 (KB3185319). The site is unusable after the error is thrown.

```
Error: Ungültiges Argument.
   at t.prototype.setText (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:934:4191)
   at View_e0.prototype.detectChangesInternal (Function code:68:5)
   at t.prototype.detectChanges (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1837:5744)
   at t.prototype.internalDetectChanges (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1837:5537)
   at View_e1.prototype.detectChangesInternal (Function code:81:3)
   at t.prototype.detectChanges (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1837:5744)
   at t.prototype.detectChangesInNestedViews (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1844:760)
   at View_e0.prototype.detectChangesInternal (Function code:195:3)
   at t.prototype.detectChanges (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1837:5744)
   at t.prototype.internalDetectChanges (https://192.168.3.79/vendor.b93e942e7ac91f17c2bc.bundle.js:1837:5537)
   at View_e2.prototype.detectChangesInternal (Funct
```

**Comment by anthonynsimon** [comment]
I just migrated angular to the latest version, this was a known issue with some versions of angular. Maybe you could try out if now it's fixed when you have time?

**Comment by Nick-Triller** [comment]
Unfortunately, the behaviour can be reproduced with the current code, too.

```
ORIGINAL STACKTRACE:
Error: Invalid Argument.
   at t.prototype.setText (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:688:4144)
   at t.prototype.detectChangesInternal (https://192.168.99.100/main.e866a3fdf70c026af960.bundle.js:1:56201)
   at t.prototype.detectChanges (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:660:5744)
   at t.prototype.internalDetectChanges (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:660:5537)
   at t.prototype.detectChangesInternal (https://192.168.99.100/main.e866a3fdf70c026af960.bundle.js:1:365510)
   at t.prototype.detectChanges (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:660:5744)
   at t.prototype.detectChangesInNestedViews (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:667:760)
   at t.prototype.detectChangesInternal (https://192.168.99.100/main.e866a3fdf70c026af960.bundle.js:1:369638)
   at t.prototype.detectChanges (https://192.168.99.100/vendor.75698a756967175c18a9.bundle.js:660:5744)
   at t.prototype.internalDet
```
